name: BOOHER
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5484
title: 'BOOHER ||| Rock N Roll Music From Austin, Texas'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#adabb0'
    - '#000a02'
    - '#82808b'
    - '#715f11'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
