typography_spectrum: 0.5484
color:
  brandColors:
    - '#fbfbfb'
    - '#adabb0'
    - '#000a02'
    - '#82808b'
    - '#715f11'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25756
analytics:
  google: null
  facebook: null
  twitter: null
name: BOOHER
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: BOOHER
description: 'Rock N Roll Music |||  Austin, Texas'
purpose: []
