name: BOOHER
favicon: null
layout_spectrum: 0.32377
typography_spectrum: 0.5484
title: 'Rock N Roll Music From Austin, Texas'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b7d7dd'
    - '#3a4734'
    - '#e4282e'
    - '#537f45'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
